### ISSUE TITLE
繁体分词支持吗？

### ISSUE THREAD

**Issue by orchestor** [ownthink/Jiagu#1]
比如：我對外訓的記憶就是滿滿的黑咖啡

分词结果：

['我', '對外訓', '的', '記憶', '就是', '滿', '滿', '的', '黑', '咖啡']
换成简体后
['我', '对', '外训', '的', '记忆', '就是', '满满', '的', '黑', '咖啡']

**Comment by ownthink** [comment]
支持的哈，不过每个分词标准不一样，这个需要看具体需求的。

**Comment by ownthink** [comment]
@orchestor 等有空了，可以专门训练一个繁体分词标准。

**Comment by orchestor** [comment]
@ownthink 我帮你训练啊，加个wechat吧。

**Comment by ownthink** [comment]
@orchestor 可以啊，加下我们QQ群90780053哈

**Comment by ownthink** [comment]
@orchestor 微信MrYener

**Comment by jience** [comment]
opencc就可以转换啊

**Comment by dirtdust** [comment]
> opencc就可以转换啊
谢谢建议哈，我们尝试下。后续会支持繁体中文的
