### ISSUE TITLE
分词效果很差，自定义分词模型加载出错

### ISSUE THREAD

**Issue by chasingML** [ownthink/Jiagu#11]
首先感谢大佬的辛苦付出和奉献精神，我在使用这个工具的时候遇到以下问题：
1、分词的时候，很多公司名字都无法准确分开，如：
sent = '和无插件。阿里大华腾讯百度 CloudFabric 方案通过与 Ansible 的集成部署，可以有效帮助客户实现更'
words = jiagu.cut(sent)
print(words)
结果是：['和', '无', '插', '件', '。', '阿里大华腾', '讯', '百', '度', ' ', 'Cloud', 'Fabric', ' ', '方案', '通过', '与', ' ', 'Ansible', ' ', '的', '集成部署', '，', '可以', '有效', '帮助', '客户', '实现', '更']
分词正确率是真的比jieba高吗，是在怎样的环境下比较的呢
2、词性和ner，都是字符级别的？如果是这样那这个不合理吧，而且返回的结果展示以元组或字典的形式可能更好吧，这样能够清楚看到每个词的词性和实体类型。
3、我从你们项目下面下载下来的自定义分词模型文件，在导入的时候会出现错误：
Traceback (most recent call last):
  File "/ddhome/usr/eclipse-workspace/huawei/huawei-libs/huawei-learnings/huawei-learning-server/python-module/demo.py", line 170, in <module>
    jiagu.load_model('/usr/local/lib/python3.6/site-packages/jiagu/extra_data/msr.model')
  File "/usr/local/lib/python3.6/site-packages/jiagu/analyze.py", line 44, in load_model
    self.seg_model = bilstm_crf.Predict(model_path)
  File "/usr/local/lib/python3.6/site-packages/jiagu/bilstm_crf.py", line 15, in __init__
    model, char_to_id, id_to_tag = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x0a'.
谢谢大佬

**Comment by ownthink** [comment]
1. 由于采用的是深度学习的模型，而训练语料我们目前只是针对九几年的语料，所以阿里，腾讯这些识别效果不好属于正常的，后面我们将会加强这方面的训练，添加自定义字典等等来弥补。测试环境可以参加下这里哈，https://github.com/ownthink/evaluation
2. 词性是词级别的，ner是字符级别的，由于ner采用词级别的处理起来会比较麻烦，所以目前先采用字级别的，等后面有时间了，将会采用词级别的，然后就可以单独一个函数三元组展示结果了。
3. 这个问题我还真没遇到过，可以加群90780053发下其他信息的截图，我们一起看下哈。

**Comment by dirtdust** [comment]
@chasingML 也可以尝试使用mmseg分词算法

**Comment by chasingML** [comment]
@dirtdust 用过了，看起来像英文单词都无法识别，都被按字母分成一个个字符了，而且就纯汉字效果也比较差

**Comment by dirtdust** [comment]
@chasingML 欢迎使用，之前的测评效果是比结巴要好些（使用的是jieba的词典），目前为了保持速度（但仍然是jieba的3倍），英文以及数字还没有做处理，后续会对速度继续优化。

**Comment by chasingML** [comment]
@ownthink 
我尝试过了，词性也是字符级别的吧，比如：
import jiagu
sent = '结婚的和尚未结婚的和无插件。what阿里大华腾讯百度 CloudFabric 方案通过与 Ansible 的集成部署，可以有效帮助客户实现更'
# jiagu.load_model('/usr/local/lib/python3.6/site-packages/jiagu/extra_data/msr.model')
words = jiagu.cut(sent, model='mmseg')
print(words)
['结婚', '的', '和尚', '未', '结婚', '的', '和', '无', '插件', '。', 'w', 'h', 'a', 't', '阿', '里', '大', '华', '腾', '讯', '百度', ' ', 'C', 'l', 'o', 'u', 'd', 'F', 'a', 'b', 'r', 'i', 'c', ' ', '方案', '通过', '与', ' ', 'A', 'n', 's', 'i', 'b', 'l', 'e', ' ', '的', '集成', '部署', '，', '可以', '有效', '帮助', '客户', '实现', '更']
mypos = jiagu.pos(sent)
print(mypos)
['v', 'n', 'u', 'c', 'd', 'd', 'v', 'n', 'u', 'c', 'v', 'v', 'n', 'w', 'n', 'ws', 'ws', 'ws', 'h', 'nd', 'a', 'n', 'v', 'n', 'm', 'q', 'm', 'ws', 'ws', 'ws', 'ws', 'w', 'ws', 'ws', 'ws', 'ws', 'ws', 'ws', 'ws', 'q', 'n', 'v', 'u', 'c', 'ws', 'ws', 'ws', 'ws', 'ws', 'ws', 'ws', 'ws', 'ws', 'u', 'n', 'v', 'n', 'n', 'w', 'vu', 'p', 'v', 'n', 'v', 'v', 'n', 'n', 'a', 'v', 'd']
sent和mypos长度是一致的，这不就说明是每个字符都对应着一个词性了吗
导入自定义模型的问题，那几个模型我是从你们项目下的test/extra_data/model下下载下来的，我的代码如下：
import jiagu
sent = '结婚的和尚未结婚的和无插件。what阿里大华腾讯百度 CloudFabric 方案通过与 Ansible 的集成部署，可以有效帮助客户实现更'
jiagu.load_model('/usr/local/lib/python3.6/site-packages/jiagu/extra_data/msr.model')
words = jiagu.cut(sent, model='mmseg')
print(words)
错误如下：
Traceback (most recent call last):
    jiagu.load_model('/usr/local/lib/python3.6/site-packages/jiagu/extra_data/msr.model')
  File "/usr/local/lib/python3.6/site-packages/jiagu/analyze.py", line 44, in load_model
    self.seg_model = bilstm_crf.Predict(model_path)
  File "/usr/local/lib/python3.6/site-packages/jiagu/bilstm_crf.py", line 15, in __init__
    model, char_to_id, id_to_tag = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by ownthink** [comment]
@chasingML 不是这样子用的哈，后面我们将会对这个做屏蔽。正确使用方式如下：

import jiagu

#jiagu.init() # 可手动初始化，也可以动态初始化

text = '厦门明天会不会下雨'

words = jiagu.seg(text) # 分词
print(words)

pos = jiagu.pos(words) # 词性标注
print(pos)

ner = jiagu.ner(text) # 命名实体识别
print(ner)

是将词语列表传入到pos哈。

**Comment by chasingML** [comment]
好的，谢谢大佬

**Comment by dirtdust** [comment]
@chasingML 问题收到，应该是mmseg的词典问题，已经在修复中了。

**Comment by chasingML** [comment]
@dirtdust 感谢感谢
