### ISSUE TITLE
关键词抽取模型效果不好

### ISSUE THREAD

**Issue by Little-girl-1992** [ownthink/Jiagu#17]
text = '宁卧庄社区迷你少年文化宫举办“团团圆圆过元宵”猜灯谜活动'
keywords = jiagu.keywords(text, 5)
print(keywords)
['谜', '迷', '灯', '猜', '元宵']

**Comment by ownthink** [comment]
@Little-girl-1992 输入的文本太短了，你可以像我们例子那样的，给出一大段的文本。
