### ISSUE TITLE
添加短文本相似度计算功能

### ISSUE THREAD

**Issue by ami66** [ownthink/Jiagu#22]
希望添加短文本相似度计算的功能

**Comment by ownthink** [comment]
@ami66 理论上是可以添加的，不过这会使安装包一直增大，所以还需要考虑下

**Comment by ami66** [comment]
网速一般情况下，我机子上安装大概要十分钟，所以现在的安装包不算大

**Comment by ownthink** [comment]
@ami66 十分钟其实已经非常久了，建议你修改下pip源，关于短文本相似度的，我以后有时间了再新开一个项目吧
