### ISSUE TITLE
tensorflow2.0删除了contrib导致无法使用

### ISSUE THREAD

**Issue by wk448378469** [ownthink/Jiagu#24]
如标题

**Comment by ownthink** [comment]
等2.0稳定后，我们才会对2.0进行支持。





------------------ 原始邮件 ------------------
发件人: "王凯"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 中午11:27
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ownthink/Jiagu] tensorflow2.0删除了contrib导致无法使用 (#24)




如标题
