### ISSUE TITLE
启动jiagu后无响应

### ISSUE THREAD

**Issue by stevenkwong** [ownthink/Jiagu#25]
- jiagu使用pip安装，安装成功且import没有报错

import jiagu
成功，接下来再输入指令就会出现无响应的情况；

Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jiagu
>>> text = '萧峰（1060~1093年），汉名乔峰，契丹乙室部人。金庸武侠小说《天龙八部》的男主角，辽国属珊军总教头萧远山之子。'

系统环境：
- CentOS release 6.9 (Final)
- linux 内核 2.6.32-696.20.1.el6.x86_64
- tf == 1.8.0

感谢你们的贡献，期待答复

**Comment by ownthink** [comment]
我测试了下你那句是没有抽取到的，可以试试以下的代码。


import jiagu


text = '刘德华（Andy Lau），1961年9月27日出生于中国香港，演员、歌手、作词人、制片人。'


result = jiagu.knowledge(text)


print(result)




------------------
郑文裕


 




------------------ 原始邮件 ------------------
发件人: "steven kwong"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 下午4:44
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ownthink/Jiagu] 启动jiagu后无响应 (#25)



 
jiagu使用pip安装，安装成功且import没有报错
  
import jiagu
 成功，接下来再输入指令就会出现无响应的情况；
 `Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06)
 [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
 Type "help", "copyright", "credits" or "license" for more information.
    
import jiagu
 text = '萧峰（1060~1093年），汉名乔峰，契丹乙室部人。金庸武侠小说《天龙八部》的男主角，辽国属珊军总教头萧远山之子。'`
    
系统环境：
  
CentOS release 6.9 (Final)
 
linux 内核 2.6.32-696.20.1.el6.x86_64
 
tf == 1.8.0
  
感谢你们的贡献，期待答复

**Comment by stevenkwong** [comment]
你好，我这边还不是抽取不到的问题；我这边是import jiagu之后，在同一个交互窗口输入指令就有大概率会一直无响应

**Comment by ownthink** [comment]
那可能就是电脑问题了，你换台机器测试下看看




------------------ 原始邮件 ------------------
发件人: "steven kwong"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 下午5:37
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "郑文裕"<158760520@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ownthink/Jiagu] 启动jiagu后无响应 (#25)




你好，我这边还不是抽取不到的问题；我这边是import jiagu之后，在同一个交互窗口输入指令就有大概率会一直无响应

**Comment by stevenkwong** [comment]
发现跟系统也没关系，用notebook启动又是可以的，就是从linux窗口进入python的交互模型后会出现这个问题
