### ISSUE TITLE
用jiagu有警告，不知道怎么解决

### ISSUE THREAD

**Issue by Ericliu68** [ownthink/Jiagu#27]
WARNING:tensorflow:From /anaconda3/envs/nlp/lib/python3.6/site-packages/jiagu/bilstm_crf.py:28: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From /anaconda3/envs/nlp/lib/python3.6/site-packages/jiagu/bilstm_crf.py:40: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

tensorflow==1.14，python==3.6.8

不知道为什么总是警告

**Comment by ownthink** [comment]
是这样的，因为tensorflow升级了，尤其是tensorflow 2.0以后很多接口都要换掉。

**Comment by Ericliu68** [comment]
> 是这样的，因为tensorflow升级了，尤其是tensorflow 2.0以后很多接口都要换掉。

不好意思，我是技术小白，我还想问一下，现在的jiagu版本是适配tensorflow那个版本的接口呢？

**Comment by ownthink** [comment]
@Ericliu68 最好用1.6版本的

**Comment by Ericliu68** [comment]
> @Ericliu68 最好用1.6版本的

谢谢
