### ISSUE TITLE
pip 安装提示找不到tensorflow1.6

### ISSUE THREAD

**Issue by 91yuan** [ownthink/Jiagu#28]
ERROR: Could not find a version that satisfies the requirement tensorflow>=1.6.0 (from jiagu) (from versions: none)
ERROR: No matching distribution found for tensorflow>=1.6.0 (from jiagu)

**Comment by ownthink** [comment]
由于你pip源没有tensorflow引起的，可以pip3 install -U pip 更新下pip

**Comment by 91yuan** [comment]
谢谢，抱歉，因为之前没弄过python和pip。所以还是没搞定。如果能提示一下怎么解决就谢谢了。要不然，我就明天搜一下，看看怎么弄。🙂
C:\Users\a'su's>pip install -U jiagu
Requirement already up-to-date: jiagu in c:\users\a'su's\appdata\local\programs\python\python37-32\lib\site-packages\jiagu-0.1.8-py3.7.egg (0.1.8)
Collecting tensorflow>=1.6.0 (from jiagu)
  ERROR: Could not find a version that satisfies the requirement tensorflow>=1.6.0 (from jiagu) (from versions: none)
ERROR: No matching distribution found for tensorflow>=1.6.0 (from jiagu)

C:\Users\a'su's>pip install tensorflow==1.6.0
Collecting tensorflow==1.6.0
  ERROR: Could not find a version that satisfies the requirement tensorflow==1.6.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.6.0

C:\Users\a'su's>pip install tensorflow-gpu==1.6.0
Collecting tensorflow-gpu==1.6.0
  ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.6.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu==1.6.0
C:\Users\a'su's>pip3 install -U pip
Requirement already up-to-date: pip in c:\users\a'su's\appdata\local\programs\python\python37-32\lib\site-packages (19.2.3)

**Comment by ownthink** [comment]
pip3 install -U jiagu


你可以加入QQ群讨论：90780053



 




------------------ 原始邮件 ------------------
发件人: "91yuan"<notifications@github.com>;
发送时间: 2019年10月13日(星期天) 晚上9:43
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "郑文裕"<158760520@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ownthink/Jiagu] pip 安装提示找不到tensorflow1.6 (#28)




谢谢，抱歉，因为之前没弄过python和pip。所以还是没搞定。如果能提示一下怎么解决就谢谢了。要不然，我就明天搜一下，看看怎么弄。🙂
 C:\Users\a'su's>pip install -U jiagu
 Requirement already up-to-date: jiagu in c:\users\a'su's\appdata\local\programs\python\python37-32\lib\site-packages\jiagu-0.1.8-py3.7.egg (0.1.8)
 Collecting tensorflow>=1.6.0 (from jiagu)
 ERROR: Could not find a version that satisfies the requirement tensorflow>=1.6.0 (from jiagu) (from versions: none)
 ERROR: No matching distribution found for tensorflow>=1.6.0 (from jiagu)
 
C:\Users\a'su's>pip install tensorflow==1.6.0
 Collecting tensorflow==1.6.0
 ERROR: Could not find a version that satisfies the requirement tensorflow==1.6.0 (from versions: none)
 ERROR: No matching distribution found for tensorflow==1.6.0
 
C:\Users\a'su's>pip install tensorflow-gpu==1.6.0
 Collecting tensorflow-gpu==1.6.0
 ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.6.0 (from versions: none)
 ERROR: No matching distribution found for tensorflow-gpu==1.6.0
 C:\Users\a'su's>pip3 install -U pip
 Requirement already up-to-date: pip in c:\users\a'su's\appdata\local\programs\python\python37-32\lib\site-packages (19.2.3)

**Comment by 91yuan** [comment]
可能是我python版本太高的问题。我降一下版本试试

**Comment by ownthink** [comment]
可以试试python3.6的




------------------ 原始邮件 ------------------
发件人: "91yuan"<notifications@github.com>;
发送时间: 2019年10月13日(星期天) 晚上9:45
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "郑文裕"<158760520@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ownthink/Jiagu] pip 安装提示找不到tensorflow1.6 (#28)




可能是我python版本太高的问题。我降一下版本试试

**Comment by cchjkl** [comment]
2019年11月7号
安装jiagu时默认装的2.0版本的tensorflow，运行“情感分析”那个程序时错误如下：
ModuleNotFoundError: No module named 'tensorflow.contrib'

只好卸载了2.0版本的，安装1.6版本的tensorflow，结果告诉我找不到  ：
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0)
ERROR: No matching distribution found for tensorflow==1.6.0

只好装的这里面最老的一版1.13.0rc1，终于运行成功，费了半天劲。。

**Comment by ownthink** [comment]
非常抱歉，由于tensorflow更新了，我们也很头疼，去tensorflow版本也在开发了，下个版本更新。。。

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cchjkl"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 晚上9:30
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] pip 安装提示找不到tensorflow1.6 (#28)




2019年11月7号
 安装jiagu时默认装的2.0版本的tensorflow，运行“情感分析”那个程序时错误如下：
 ModuleNotFoundError: No module named 'tensorflow.contrib'
 
只好卸载了2.0版本的，安装1.6版本的tensorflow，结果告诉我找不到  ：
 ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0)
 ERROR: No matching distribution found for tensorflow==1.6.0
 
只好装的这里面最老的一版1.13.0rc1，终于运行成功，费了半天劲。。

**Comment by AndyCheungCH** [comment]
> 2019年11月7号
> 安装jiagu时默认装的2.0版本的tensorflow，运行“情感分析”那个程序时错误如下：
> ModuleNotFoundError: No module named 'tensorflow.contrib'
> 
> 只好卸载了2.0版本的，安装1.6版本的tensorflow，结果告诉我找不到 ：
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0)
> ERROR: No matching distribution found for tensorflow==1.6.0
> 
> 只好装的这里面最老的一版1.13.0rc1，终于运行成功，费了半天劲。。

谢谢！我也遇到了同样的问题，按照你的方案解决了！
