### ISSUE TITLE
模型训练方式的问题

### ISSUE THREAD

**Issue by Vector-Cross** [ownthink/Jiagu#30]
感谢大佬的分享。非常实用。

请问，能提供一下分词器模型的训练方式吗？稍微指导一下方向也好

**Comment by ownthink** [comment]
下个版本已经在准备中，到时候提供训练方法。


------------------
郑文裕


 




------------------ 原始邮件 ------------------
发件人: "Vector-Cross"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午5:30
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ownthink/Jiagu] 模型训练方式的问题 (#30)




感谢大佬的分享。非常实用。
 
请问，能提供一下分词器模型的训练方式吗？稍微指导一下方向也好

**Comment by Vector-Cross** [comment]
正在播放《相当优秀》
●━━━───────── 03:11
⇆     ◁   ㅤㅤ❚❚    ㅤㅤ▷      ㅤ

**Comment by Halfwaygo** [comment]
没有添加新词功能吗
