### ISSUE TITLE
三元组抽取如何进行训练呢

### ISSUE THREAD

**Issue by Geo-hou** [ownthink/Jiagu#32]

**Comment by ownthink** [comment]
后面版本将会给出训练过程

**Comment by wangwanglee** [comment]
您好，请问近期会更新训练过程吗，现在作业需要做一个特定领域的关系抽取，麻烦了

**Comment by ownthink** [comment]
&nbsp;已经在更新了，不过没那么快哈，欢迎持续关注。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangwanglee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 下午5:27
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 三元组抽取如何进行训练呢 (#32)




您好，请问近期会更新训练过程吗，现在作业需要做一个特定领域的关系抽取，麻烦了

**Comment by wangwanglee** [comment]
好的，谢谢您
