### ISSUE TITLE
什么时间能把三元组抽取的模型代码开放出来?

### ISSUE THREAD

**Issue by gs80140** [ownthink/Jiagu#34]
这个开源代码只提供训练好的模型, 什么时候可以把如果训练模型的代码开源出来?
这个训练好的模型对我来说没啥用, 我随便弄个文本都抽不出来三元组

**Comment by ownthink** [comment]
别催了，我尽快，我也得先解决吃饭问题不是

郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gs80140"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 下午3:18
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/Jiagu] 什么时间能把三元组抽取的模型代码开放出来? (#34)




这个开源代码只提供训练好的模型, 什么时候可以把如果训练模型的代码开源出来?
 这个训练好的模型对我来说没啥用, 我随便弄个文本都抽不出来三元组
