### ISSUE TITLE
运行test/test.py时报错

### ISSUE THREAD

**Issue by Gezelligh3id** [ownthink/Jiagu#35]
错误为：
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    words = jiagu.seg(text, model="mmseg")  # mmseg分词
TypeError: seg() got an unexpected keyword argument 'model'

环境为tensorflow1.6, jiagu0.1.8, numpy1.16.4

**Comment by ownthink** [comment]
mmseg 已经移除

**Comment by Gezelligh3id** [comment]
谢谢大佬，祝您工作顺利，生活愉快

**Comment by ownthink** [comment]
thk.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gezelligh3id"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午3:48
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 运行test/test.py时报错 (#35)




谢谢大佬，祝您工作顺利，生活愉快
