### ISSUE TITLE
jiagu.dict

### ISSUE THREAD

**Issue by yongzhuo** [ownthink/Jiagu#38]
有点好奇你们的jiagu.dict中词语和词频是怎么获取的，
对比发现用动态规划查找最大概率分词，
你们的词典要比jieba默认的词典效果要好一点。

**Comment by ownthink** [comment]
jiagu所有的语料词频全部采用人工标注的语料，jieba有很大一部分是使用ICTCLAS分词后统计的，所以jiagu的是会比jieba的效果好的。



郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yongzhuo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午4:15
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/Jiagu] jiagu.dict (#38)




有点好奇你们的jiagu.dict中词语和词频是怎么获取的，
 对比发现用动态规划查找最大概率分词，
 你们的词典要比jieba默认的词典效果要好一点。

**Comment by yongzhuo** [comment]
ok, 了解
