### ISSUE TITLE
知识关系提取

### ISSUE THREAD

**Issue by graphnj** [ownthink/Jiagu#43]
text = '新疆大学（Xinjiang University），简称“新大”，位于新疆维吾尔自治区首府乌鲁木齐，是世界一流大学建设高校、全国重点大学'
knowledge = jiagu.knowledge(text)
print(knowledge)
output:[['新疆大学', '简称', '新大']]

text = '新疆大学（Xinjiang University），简称“新小”，位于新疆维吾尔自治区首府乌鲁木齐，是世界一流大学建设高校、全国重点大学'
knowledge = jiagu.knowledge(text)
print(knowledge)

将新大换成新小， 新闻  等其他词汇就都不行了..

**Comment by ownthink** [comment]
这肯定的啊，新大是简称，里面蕴含了许多的语义。




不过这些模型都是去tensorflow后的，性能比较差，可以用旧版本的，旧版本抽取性能好。


如果不急着用，我这边有个新的，不过还没弄好。



郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"graphnj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 下午4:10
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/Jiagu] 知识关系提取 (#43)




text = '新疆大学（Xinjiang University），简称“新大”，位于新疆维吾尔自治区首府乌鲁木齐，是世界一流大学建设高校、全国重点大学'
 knowledge = jiagu.knowledge(text)
 print(knowledge)
 output:[['新疆大学', '简称', '新大']]
 
text = '新疆大学（Xinjiang University），简称“新小”，位于新疆维吾尔自治区首府乌鲁木齐，是世界一流大学建设高校、全国重点大学'
 knowledge = jiagu.knowledge(text)
 print(knowledge)
 
将新大换成新小， 新闻  等其他词汇就都不行了..

**Comment by graphnj** [comment]
谢谢回复，
不过这未知知识抽取，应该考虑不到语义吧，
text = '新疆中心小学，简称“新小”，位于新疆'
这种也该提出来吧  ， 我不是专业的， 以前感兴趣临时用下啊，说错了见谅啊

**Comment by ownthink** [comment]
&nbsp;没事的，这方面目前做的不好，我已经开始内部新开一个项目专门弄这个了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"graphnj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 晚上7:42
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43)




谢谢回复，
 不过这未知知识抽取，应该考虑不到语义吧，
 text = '新疆中心小学，简称“新小”，位于新疆'
 这种也该提出来吧  ， 我不是专业的， 以前感兴趣临时用下啊，说错了见谅啊

**Comment by shaofengzeng** [comment]
请问?用到的算法是什么？

**Comment by 25thengineer** [comment]
请问含tf的版本具体是哪一版以前呢？

**Comment by ownthink** [comment]
&nbsp;0.1.7还是0.1.8 忘记了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Utah Xef"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 下午3:57
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43)





 
请问含tf的版本具体是哪一版以前呢？

**Comment by 25thengineer** [comment]
好的，谢谢前辈~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yener"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 下午4:01
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"qowurxbxyksufpshwoudnb"<wenhuafly@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43)





 &amp;nbsp;0.1.7还是0.1.8 忘记了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Utah Xef"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 下午3:57 
 收件人:&amp;nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"郑文裕"<158760520@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43) 
 
 
 
 
 
   
 请问含tf的版本具体是哪一版以前呢？

**Comment by BI4O** [comment]
我试了好多的句子，我从0.1.8就开始用了，三元组抽取功能是真的不好使....是我句子的结构原因吗？我自己写的句子就几乎没有可以提取出来三元组的

**Comment by ownthink** [comment]
只能抽取百科的描述啦



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BI4O"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 下午4:09
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43)





 
我试了好多的句子，我从0.1.8就开始用了，三元组抽取功能是真的不好使....是我句子的结构原因吗？我自己写的句子就几乎没有可以提取出来三元组的

**Comment by 25thengineer** [comment]
忽然发现项目的releases里面没东西，该怎么找到0.0.18版本呢？

**Comment by ownthink** [comment]
&nbsp;pypi上面去下载




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Utah Xef"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 下午4:53
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43)





 
忽然发现项目的releases里面没东西，该怎么找到0.0.18版本呢？

**Comment by 25thengineer** [comment]
谢谢~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yener"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 下午4:57
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"Clairaut"<wenhuafly@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43)





 &amp;nbsp;pypi上面去下载 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Utah Xef"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月26日(星期四) 下午4:53 
 收件人:&amp;nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"郑文裕"<158760520@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ownthink/Jiagu] 知识关系提取 (#43) 
 
 
 
 
 
   
 忽然发现项目的releases里面没东西，该怎么找到0.0.18版本呢？
