### ISSUE TITLE
分词对比测试使用的是默认的还是感知机的？

### ISSUE THREAD

**Issue by lijingquan1** [ownthink/Jiagu#45]
看了分词的部分的代码（default）好像和jieba是一样的，所以想知道这个测试结果是基于感知机（是感知机吧？）模型的吗？谢谢

**Comment by ownthink** [comment]
其实最开始是BILSTM+CRF啦，但是由于依赖于tensorflow，所以很多人安装不上，考虑到便用性，所以后面改成感知机了。default是和jieba一样的，但是字典全部采用人工标注的数据集进行统计的，而jieba的字典大部分是其他分词工具分出来的结果。

郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lijingquan1"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 凌晨1:11
收件人:&nbsp;"ownthink/Jiagu"<Jiagu@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/Jiagu] 分词对比测试使用的是默认的还是感知机的？ (#45)




看了分词的部分的代码（default）好像和jieba是一样的，所以想知道这个测试结果是基于感知机（是感知机吧？）模型的吗？谢谢

**Comment by lijingquan1** [comment]
那HMM部分有做优化吗？
