### ISSUE TITLE
自动摘要代码报错

### ISSUE THREAD

**Issue by zhiyongLiu1114** [ownthink/Jiagu#5]
module 'jiagu' has no attribute 'cut'

文件名非jiagu

**Comment by ownthink** [comment]
方便提供下python的版本和用的哪个系统吗，我们这边系统centos7，python34，python36都没法复现这个问题。

**Comment by ownthink** [comment]
看下是否没安装最新版，pip3 install -U jiagu

**Comment by zhiyongLiu1114** [comment]
from pyhanlp import *
import jiagu

这两行代码同时存在会有这个问题

**Comment by zhiyongLiu1114** [comment]
试了一下，现在又没有这个bug了。。。

**Comment by ownthink** [comment]
不会吧，这也行，还真没遇到过

**Comment by zhiyongLiu1114** [comment]
自动摘要分句以句号结尾，使得结果显得冗长，建议改进

**Comment by dirtdust** [comment]
非常感谢建议，我们会对返回的格式进行进一步的优化
