### ISSUE TITLE
词性标注错误很多

### ISSUE THREAD

**Issue by yaleimeng** [ownthink/Jiagu#6]
其实随便一段话试一下就能发现，对于“的”、“有”等高频词标注错误率极高，完全不具备可用性。
以下面片段为例：
Jiagu分词与标注结果：
思知/v 是/v 作者/vl 的/v 一个/k 理想/u 国/m ，/q 作者/n 在/v 人工智能/n 方面/w 不断/v 努力/k 着/p ，/n 希望/n 有/n 一天/n 能够/n 出现/n 独立思考/d 的/v 人工智能机器人/v ，/n 虽然/u 明知道/w 短期/v 内/v 不/v 可能/m 实现/nt ，/vu 但/v 却/vd 一直/n 向着/a 他/v 的/v 梦/v 执着/u 前行/n 着/n 。/n 

jieba分词与标注结果：
思知/n 是/v 作者/n 的/uj 一个/m 理想国/n ，/x 作者/n 在/p 人工智能/n 方面/n 不断/d 努力/ad 着/uz ，/x 希望/v 有/v 一天/m 能够/v 出现/v 独立思考/nr 的/uj 人工智能/n 机器人/n ，/x 虽然/c 明/a 知道/v 短期内/n 不/d 可能/v 实现/v ，/x 但/c 却/d 一直/d 向着/p 他/r 的/uj 梦/n 执着/v 前行/v 着/uz 。/x '/x 

PS-原文：
思知是作者的一个理想国，作者在人工智能方面不断努力着，希望有一天能够出现独立思考的人工智能机器人，虽然明知道短期内不可能实现，但却一直向着他的梦执着前行着。

**Comment by ownthink** [comment]
这些模型还在训练哈，因为就笔记本，目前仅仅是开发的初步阶段

**Comment by dirtdust** [comment]
非常感谢提供的建议，词性准确率的问题我们还在继续优化中，后续会放出更加完善的版本。
