### ISSUE TITLE
我安装了jiagu这个包，可以加载自己的词典，按照里面的词进行分词，提取关键词吗？因为好多人名的姓跟名都给分开了

### ISSUE THREAD

**Issue by wjy3326** [ownthink/Jiagu#71]

**Comment by ownthink** [comment]
提取关键词的不支持自定义




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/Jiagu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 下午5:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ownthink/Jiagu] 我安装了jiagu这个包，可以加载自己的词典，按照里面的词进行分词，提取关键词吗？因为好多人名的姓跟名都给分开了 (Issue #71)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wjy3326** [comment]
可以优化吗

**Comment by ownthink** [comment]
&nbsp;你可以自己改哈，jiagu也可以改。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/Jiagu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 我安装了jiagu这个包，可以加载自己的词典，按照里面的词进行分词，提取关键词吗？因为好多人名的姓跟名都给分开了 (Issue #71)





 
可以优化吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wjy3326** [comment]
怎么自己改呢

**Comment by wjy3326** [comment]
能不能用我自己的代码分词，然后用jiagu提取关键词？在哪里改？

**Comment by wjy3326** [comment]
他把三个字的人名都给分开了，无一幸免

**Comment by ownthink** [comment]
&nbsp;不行的哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/Jiagu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 我安装了jiagu这个包，可以加载自己的词典，按照里面的词进行分词，提取关键词吗？因为好多人名的姓跟名都给分开了 (Issue #71)





 
能不能用我自己的代码分词，然后用jiagu提取关键词？在哪里改？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wjy3326** [comment]
。。。你们是用什么方法抽取关键词，是先分词吗

**Comment by ownthink** [comment]
这是基于概率的，确实会出现这种情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/Jiagu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ownthink/Jiagu] 我安装了jiagu这个包，可以加载自己的词典，按照里面的词进行分词，提取关键词吗？因为好多人名的姓跟名都给分开了 (Issue #71)





 
他把三个字的人名都给分开了，无一幸免
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wjy3326** [comment]
你们的提取关键词的代码在哪里？我怎么没找到jiagu.keywords在哪呢
